---
output:
  html_document: 
    toc: true
    toc_float: true
---

# FORm - the FOR2591 Online Repository Form
For a research project in the German FOR2591 consortium (Severity assessment) several laboratories provided data. In order to harmonize the data collection, FORm was invented. For animal studies, the general format of FORm is useful for data collection.
FORm can be downloaded here as an Excel file with multiple tabs.

FORm follows my tutorial on Data collection.

## FORm framework
FORm is built in several tabs. It is good practice to give each study a separate FORm. The "information" tab can be used for study meta-information and documentation.

1. Readme - some general guidelines for correct data entry
2. Information - General study information & ARRIVE Guidelines
3. Data - Data are formatted in the long format (variables in columns and cases in rows)
4. SIF - Sample information file (each row can provide additional information and/or meta information on the data)
5. Comments - a free to use field for comments

## Download the latest version of FORm
[Get FORm here!](https://talbotsr.com/files/FORm_1.1.1.xls)

