---
output:
  html_document: 
    toc: true
    toc_float: true
---
  
## Impressum (Imprint/Legal disclosure)

**Angaben gemäß § 5 TMG **   
Dr. Steven R. Talbot  
Lehrter Str. 51  
D-30559 Hannover  
 
Kontakt: info@talbot-science.de  
Telefon: +49 – (0) 511 373 967 93  

**Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:**  
Dr. Steven R. Talbot  
Lehrter Str. 51  
D-30559 Hannover  

Plattform der EU zur außergerichtlichen [Online-Streitbeilegung:](http://ec.europa.eu/consumers/odr)

Es besteht keine Bereitschaft oder Verpflichtung zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle.

## Datenschutzerklärung

### Name und Kontaktdaten des Verantwortlichen  
Dr. Steven R. Talbot  
Lehrter Str. 51  
D-30559 Hannover  
 
Kontakt: info@talbot-science.de  
Telefon: +49 – (0) 511 373 967 93  

### Allgemeine Hinweise
Meine Website wurde erstellt mit Dienstleistungen von 1&1 IONOS SE, Elgendorfer Str. 57, 56410 Montabaur (nachfolgend IONOS).

Beim Zugriff auf meine Webseite könnten automatisch allgemeine Informationen (sog. Server-Logfiles) erfasst. Diese beinhalten u.a. den von Ihnen verwendeten Webbrowser sowie Ihr Betriebssystem und Ihren Internet Service Provider. Diese Daten lassen keinerlei Rückschlüsse auf Ihre Person zu und werden von mir statistisch ausgewertet, um den Internetauftritt technisch und inhaltlich zu verbessern. Das Erfassen dieser Informationen ist notwendig, um den Inhalt der Webseite korrekt ausliefern zu können.  

Die Nutzung der Webseite ist grundsätzlich ohne Angabe personenbezogener Daten möglich. Soweit personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben.

Sofern Sie an mich eine Anfrage stellen, erhebe und verwende ich personenbezogene Daten von Ihnen, soweit dies zu diesem Zwecke erforderlich ist. Sämtliche personenbezogenen Daten werden nur solange gespeichert wie dies für den genannten Zweck (Bearbeitung Ihrer Anfrage) erforderlich ist. Hierbei werden steuer- und handelsrechtliche Aufbewahrungsfristen von mir berücksichtigt.

Ich weise ausdrücklich darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Vor dem Zugriff auf Daten kann nicht lückenlos geschützt werden.

Die Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich untersagt. Ausgenommen hiervon sind bestehende Geschäftsbeziehungen bzw. es liegt Ihnen eine entsprechende Einwilligung von mir vor.

Der Anbieter und alle auf dieser Website genannten Dritten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen vor. Gleiches gilt für die kommerzielle Verwendung und Weitergabe der Daten.

### Auskunfts- und Widerrufsrecht
Sie haben jederzeit das Recht, sich unentgeltlich und unverzüglich über die zu Ihrer Person erhobenen Daten zu erkundigen. Ebenfalls können Sie Ihre Zustimmung zur Verwendung Ihrer angegebenen persönlichen Daten mit Wirkung für die Zukunft widerrufen. Hierfür wenden Sie sich bitte an den im Impressum angegebenen Diensteanbieter.


