---
pagetitle: "Speaking"
output:
  html_document: 
    toc: true
    toc_float: true
---

## Invited
**2025** "Artificial Intelligence — An overview—" Vortrag auf dem Retreat des von zukunft.niedersachsen geförderten Graduierten-Kollegs 'RNApp' für RNA-Anwendungen in Medizin und Pharmazie.

**2025** Keynote zum Thema "Bayessche Statistik und fortgeschrittene Fallzahlplanung in der tierexperimentellen Forschung" in der Session 'Replace, Reduce, Refine - 3R in der Chirurgie' im Rahmen der Chirurgischen Forschungstage 2025.

**2025** TRAVELS (Towards Reproducibility and Value in the Life Sciences) Symposium am Helmholtz-Institut für Biomedizinische Technik, Aachen.

**2025** Smarter Monitoring: Data Science Innovations in Automated Home Cage Systems (FELASA 2025, Athens, Greece).

**2025** 31. Essener Informationstreffen für Tierschutzbeauftragte, Tierexperimentatoren und mit Tierversuchen befasste Behördenvertreter (Online Tagung): Künstliche Intelligenz Revolution in der tierexperimentellen Forschung?

**2025** Innovative Approaches to the 3Rs: Bayesian Statistics and Advanced Sample Size Calculations (European Molecular Imaging Meeting, EMIM 2025, Bilbao, Spain).

**2024** Improving Laboratory Animal Welfare with Advanced Data Science Methods, 2. Jahrestagung des 3R-Kompetenznetzwerks NRW (Vaals, Niederlande).

**2024** Statistical Strategies for Robust Research in the Life Sciences (European Molecular Imaging Meeting, EMIM 2024, Porto, Portugal).

**2023** Methoden der Datenwissenschaften für eine objektivere Belastungsbeurteilung 
von Versuchstieren (Nuvisan GmbH, Neu-Ulm).

**2023** Models and Insights in Translational Research 2023 Symposium: The 
Translational Power of Data Science in Severity Assessment (Faculty of Medicine, Goethe University, Frankfurt/Main).

**2023** 12th World Congress on Alternatives and Animal Use in the Life Sciences: Leveraging Data Science for Better Severity Assessment in Laboratory Animal Science (Niagara Falls, Canada).

**2023** 12th World Congress on Alternatives and Animal Use in the Life Sciences: The RELSA Score - An Evidence-Based Tool for Better Severity Assessment in Animal Research (Niagara Falls, Canada).

**2023** Charité 3R Lecture: RELSA - Relative Severity Assessment in Laboratory Animals (Charité, Berlin).  

**2023** Oxford 3Rs Symposium (University of Oxford, GB): Analysis of longitudinal
data and its application to welfare monitoring/scoring.

**2022** Max Planck Lab Animal Science Lectures (Max Planck Institute of
Immunbiology and Epigenetics, Freiburg): The Digital Fingerprint of Evidence-Based 
Methods in the Severity Assessment of Laboratory Animals.

**2022** 2nd Digital Vivarium Forum: Use of activity measurements for severity 
assessment (Tecniplast, Buguggiate (VA), Italy).

**2022** 3R Summerschool: The Digital Fingerprint of Severity in Laboratory Animals (Charité, Berlin).  

**2021** DECIDE Statistics Consensus Workshop: Towards best practice in preclinical confirmatory animal research.

**2021** 3R-Webinar (Berlin). The severity of "stress" in animal models: science & technologies - 3R-supporting approaches improving the validity of biomedical studies: The RELSA Algorithm: Approaching the Comparative Quantification of Severity in Laboratory Animals.

**2021** 27. Essener Informationstreffen für Tierschutzbeauftragte, Tierexperimentatoren und mit Tierversuchen befasste Behördenvertreter (Online Tagung): Künstliche Intelligenz - Zukunft und Chancen.

**2020** 58. Wissenschaftliche Tagung der Gesellschaft für Versuchstierkunde GV-SOLAS und 19. Fortbildungsveranstaltung der IGTP. Neue Strategien für das Composite Scoring zur Belastungsbewertung in der Versuchstierkunde (Online Workshop).

**2019** Bundesinstitut für Risikobewertung (BfR, Berlin): Quantitative Charakterisierung der Belastung von Versuchstieren (48. Seminar über Versuchstiere und Tierversuche der GV-SOLAS).

**2019** Institute of Pharmacology, Toxicology & Pharmacy (Ludwig-Maximilians-University (LMU), Munich): Conquering human bias - Feature selection for severity assessment. 

**2019** Institut für Mathematik (Universität Zürich, Zurich): An Example for Computational Methods in the Animal Sciences - Tackling Severity Assessment.

**2019** Bundesinstitut für Risikobewertung (BfR, Berlin): Body weight – a “good” predictor for severity in animal models?

**2018** FOR2591 Meeting in Rostock: Use-case „Small Data“: Online Repository & Analyis of mouse body weight data for potential severity assessment.

**2018** Institut für Versuchstierkunde (MHH, Hannover): Ratten, Tumore und Aktien - Mit Risiko dem Ende entgegen.

**2018** Institut für Versuchstierkunde (MHH, Hannover): FOR - FOR2591 Online Repository.

**2017** Institut für Versuchstierkunde (MHH, Hannover): Stress level prediction - a classification approach.

**2016** Institut für physiologische Chemie (MHH, Hannover): Predicting Myosin Dynamics using GROMACS.

**2015** Institut für Chemie und Biologie des Meeres (ICBM, Wilhelmshaven): The ESP as an example for marine ecogenomic sensors.

**2015** Institut für Chemie und Biologie des Meeres (ICBM, Wilhelmshaven):The problem of feature loss as a potential bottleneck in the detection of pathogenic bacteria.

**2011** Fraunhofer Institut für Toxikologie und Experimentelle Medizin - ITEM (Hannover): Multivariate Statistik und Analysemethoden.

**2009** Wehrwissenschaftliches Institut für Schutztechnologien - ABC Schutz (Munster): Identifikation potentieller bakteriologischer Kampfstoffe mit Ramanspektroskopie unter Nutzung von multivariater Statistik.

**2008** Hannover Messe/German Bioperspectives (Hannover) - Identification of potential bacterial biological warfare agents with spectroscopic methods using multivariate statistics. 

**2008** Robert-Koch Institut (RKI, Berlin) - Classification of potential biological warfare agents.

**2007** Institut für Technische Chemie (TCI, Hannover) - Identifikation von potentiellen BWA mit spektroskopischen Verfahren Identifikation von potentiellen biologischen Kampfstoffen mit Ramanspektrometrie.

**2007** ANGCCP Meeting (Sanitätsakademie der Bundeswehr, München) - Identification and Classification of Pathogens with Raman Spectroscopy.


## Contributions & Posters
**2025** Abdul-Hamid Emwas, Jana Tauschke, Inas Al-Younis, Elaine A. Yu, Steven R. Talbot, Helena U. Zacharias. Artificial Intelligence for Smart Data Extraction: A First Use Case for A Meta Analysis to Identify Metabolic Biomarkers in Diabetes Research. Deutsche Gesellschaft für Metabolom Forschung (DGMet, Annual Meeting Hannover).

**2025** Steven R. Talbot, Sara Lutscher. Enhancing 3R Principles with Bayesian Updating - 
A New Horizon in Sample Size Calculation for Replacement Methods. MPS Congress Brussels. 

**2025** D.T. Jacob, L. Keubler, K. Selke, M. Büttner, L. Wenzel, S. Buchheister, S. R. Talbot, S. Lutscher, A. Glasenapp, M. Bankstahl, A. Bleich, C. Häger. Severity assessment in the DSS-colitis model under metamizole pain therapy. FELASA 2025, Athens, Greece.

**2025** L. Keubler, D. Jacob, K. Selke, L. Wenzel, S. R. Talbot, A. Bleich, C. Häger. Evaluation of a prolonged adaptation period on Mouse Grimace Scale baselines, FELASA 2025, Athens, Greece.

**2025** Verena Buchecker, Lena Boldt, Ines Koska, Isabel Seiffert, Christina Möller, Katharina Aulehner, Rupert Palme, Steven R. Talbot and Heidrun Potschka. Evidence-based severity assessment and refinement measures in rodent epilepsy models. FELASA 2025, Athens, Greece.

**2025** Simone Kumstel, Tim Schreiber, Anna Richter, Sandra Lange, Steven R. Talbot, Jakob Brandstetter, Christian Junghanss and Brititte Vollmar. Analgesic refinement of a murine orthotopic xenograft model for acute lymphoblastic leukemia. FELASA 2025, Athens, Greece.

**2025** Tim Schreiber, Emily Leitner, Jakob Brandstetter, Steven R. Talbot, Rupert Palme, Brigitte Vollmar and Simone Kumstel. Pain Relief and Recovery: Comparison of Oral Analgesics for Telemeter Implantation in Mice. FELASA 2025, Athens, Greece.

**2025** Leonie Tix, Lena Kistermann, Aryo Zare, Steven R. Talbot, Anne Rix, Lisa Ernst, René H. Tolba. ndividuelle tierärztliche Betreuung von Xenopus laevis- wann besteht ein vernünftiger Grund zum Töten? DVG-Vet-Congress 2025, Berlin.

**2024** Philipp L.S. Ohland, Stephan Halle, Korbinian Brand, Steven R. Talbot. Quantifizierung der Erkrankungsschwere bei Amanitin-vergifteten Patienten durch Fusion gängiger Laborwerte. DIVI24 Kongress, Hamburg.

**2024** Philipp L.S. Ohland, Stephan Halle, Steven R. Talbot. Quantifying Disease Severity in Amanitin-Intoxicated Patients by Fusing Common Laboratory Values.

**2023  Steven R. Talbot**, Christine Häger, Heidrun Potschka, Kerstin Schwabe and André Bleich. Leveraging data science for better severity assessment in laboratory animal science. WC12 Congress Niagara Falls.

**2023 Steven R. Talbot**, Christine Häger, Anne Mallien, Dietmar Zechner, Simone Kumstel, Brigitte Vollmar and André Bleich. The RELSA score: An evidence- based tool for better severity assessment in animal research. WC12 Congress Niagara Falls.

**2023** Christine Häger, **Steven R. Talbot** and André Bleich. Multimodal welfare assessment in laboratory mice after surgery. WC12 Congress Niagara Falls.

**2023** Heidrun Potschka, Maria Reiber, Lara von Schumann, Maarten van Dijk, Verena Buchecker, Vanessa Philippi, André Bleich and **Steven Talbot**. Development of composite measure schemes for evidence-based severity assessment and refinement in neuroscientific research. WC12 Congress Niagara Falls.

**2023** Alina Ottlewski, Christine Häger, Elvis Hermann, Marion Bankstahl, **Steven R. Talbot**, Joachim K. Krauss, André Bleich and Kerstin Schwabe. Evaluation of running wheel behavior as a reliable marker for severity assessment and
humane endpoint detection in a rat model with intracranial tumor. WC12 Congress Niagara Falls.

**2023** Anne Stephanie Mallien, **Steven R. Talbot**, Laura Becker, Christiane Brandwein, Natascha Pfeiffer, Anna Munk, Verena Buchecker, Anne Rix, Jasmin Baier, Renee Girbig, Sarah Neunecker, Miriam Vogt, Rupert Palme, Andre Bleich, Fabian Kiessling, Heidrun Potschka, Sabine Chourbaji and Peter Gass. Group versus individual housing in male and female laboratory mice: A multicenter study reveals only subtle differences in severity. WC12 Congress Niagara Falls.

**2023** Christine Häger, **Steven R. Talbot** and André Bleich. Improved post-operative pain and welfare assessment in sheep. WC12 Congress Niagara Falls.

**2023** Eva Zentrich, **Steven R. Talbot**, André Bleich and
Christine Häger. alidation of clinical scoring and home-cage monitoring in a mouse model of acute colitis. WC12 Congress Niagara Falls.

**2023** Verena Buchecker, Lena Boldt, Ines Koska, Isabel Seiffert, Christina Möller, Katharina Aulehner, Rupert Palme, André Bleich, **Steven R. Talbot** and Heidrun Potschka. Evidence-based severity assessment in epilepsy models as a basis for refinement? WC12 Congress Niagara Falls.

**2023** Christine Häger, **Steven R. Talbot** and André Bleich. Insights from the home cage: Data science-driven activity analysis enables sensitive welfare assessment in colitis models. WC12 Congress Niagara Falls.

**2021** Schmidt, Teresa; Meller, Sebastian; **Talbot, Steven Roger**; Berk, Benjamin Andreas; Law, Tsz Hong; Hobbs, Sarah; Packer, Rowena Mary Anne; Volk, Holger Andreas. Urinary neurotransmitter patterns are altered in canine epilepsy. 33rd ESVN-ECVN Symposium.

**2021** Schmidt, Teresa; Meller, Sebastian; Packer, Rowena Mary Anne; **Talbot, Steven Roger**; Volk, Holger Andreas. Urinary neurotransmitter analysis in canine behavioural disorders. 33rd ESVN-ECVN Symposium.

**2021** Eva Zentrich, **Steven R. Talbot**, Andre Bleich, Christine Häger. Digital Ventilated Cage (DVC®) System – A useful tool for severity assessment in mice in an acute DSS-induced colitis model? 59. GV-SOLAS und 20. IGTP.

**2021** T. Schmidt, S. Meller, **S.R. Talbot**, B.A. Berk, T.H. Law, S.L. Hobbs, R.M.A. Packer, H.A. Volk. URINARY NEUROTRANSMITTER PATTERNS ARE ALTERED IN CANINE EPILEPSY. ESVN symposium 2021.

**2021** T. Schmidt, S. Meller, R.M.A. Packer, **S.R. Talbot**, H.A. Volk. Urinary neurotransmitter analysis in canine behavioural disorders. Journal of Veterinary Internal Medicine (JVIM); ACVIM (American College of Veterinary Internal Medicine).

**2019** Ines Koska, R. Maarten van Dijk, **Steven R. Talbot**, Isabel Seiffert, Valentina di Liberto, Christina Möller, André Bleich and Heidrun Potschka; Developing composite measure schemes for the assessment of severity in animal models, Vetpharm Symposium Munich.

**2019** Simeon O.A. Helgers, Ann-Kristin Riedesel, Laura Wassermann, Christine Häger, Steven R. Talbot, Joachim K. Krauss, André Bleich, Kerstin Schwabe; Telemetric measures in a rat model with intracranial tumor, FELASA Prague.

**2019** L. Wassermann, Ann-Kristin Riedesel, Simeon Helgers, **Steven R. Talbot**, André Bleich, Kerstin Schwabe, Christine Häger; Experimental procedures and their impact on heart rate and activity in rats, FELASA Prague.

**2019** Guanglin Tang, Nico Seume, **Steven R. Talbot**, Christine Häger, Simone Kumstel, Kerstin Abshagen, André Bleich, Brigitte Vollmar, Xianbin Zhang and Dietmar Zechner; A multifactorial distress analysis of animal models for liver fibrosis, FELASA Prague. 

**2019** S. Helgers, **S. R. Talbot**, A. - K. Riedesel, J. K. Krauss, A. Bleich, K. Schwabe; Humane endpoint determination in rat models with intracranial tumor using body weight course analysis.

**2018** Häger, C., L. Keubler, **S. Talbot**, S. Biernot, N. Weegh, M. Büttner, S. Glage, A. Bleich. Severity assessment through classification of wheel wheel-running behaviour in laboratory mice. 56th Annual Meeting of the Society for Animal Laboratory Science (GV-SOLAS), 2018, Munich, Germany

**2018** Leonie Zieglowski, Anna Kümmecke, Mareike Schulz, Lisa Ernst, **Steven Talbot**, René H. Tolba, GV-Solas Munich, Titel: Severity Assessment after visceral surgery in rats. 

**2018** Simone Kumstel, Guanglin Tang, Ahmed Abdelrahman, **Steven Talbot**, Johanna Eichberg, Edgar Wendt, Nico Seume, Kerstin Abshagen, Xianbin Zhang, Andre Bleich, Brigitte Vollmar, Dietmar Zechner; Grading of distress in gastrointestinal animal models.

**2017** Adrian Schwarzer, **Steven R Talbot**, Juliane W Schott, Anton Selich, Axel Schambach, and Michael Rothe; Molecular immortalization signature of murine HSPC.

**2016** Schwarzer, A., **Talbot, S. R.**, Dittrich-Breiholz, O., Thrasher, A. J., Gaspar, B., Modlich, U., Baum, C., Schambach, A., & Rothe, M. (2016). New Molecular Surrogate Assay for Genotoxicity Assessment of Gene Therapy Vectors (SAGA). *Blood*, 128(22), 4710. 

**2013** Gerhard Sartorius, **S. R. Talbot**; Fast classification process MAE+.

**2009** **Steven R. Talbot**, Heiko Russmann, Thomas Scheper, Medizinische B-Schutztagung, Sanitätsakademie der Bundeswehr; Identification of potential biological warfare agents with Raman spectroscopy.

**2007** **Steven R. Talbot**, Heiko Russmann, Thomas Scheper, Medizinische B-Schutztagung, Sanitätsakademie der Bundeswehr; Inactivation and detection of potential bacterial biological agents based on the spore simulant Bacillus atrophaeus.
