---
pagetitle: "Teaching"
output:
  html_document: 
    toc: true
    toc_float: true
---

## Teaching
I'm offering various courses in and around Statistics/Design of Experiments and Artificial Intelligence (AI). If you are interested in a custom course, please feel free to write me an email. At the moment, I will address roughly the following topics:

* Basic statistics
* Basic R course
* Basic Machine Learning / AI
* Basic GraphPad Prism
* When to use which statistical test?
* Power analysis & sample size calculation
* Linear & non-linear analyses / Classification
* And whatever else you can come up with around the listed topics...

For keeping things simple, in most statistics courses GraphPad Prism is used. However, you'll probably need a valid software licence for that. There is a 30 day trial version on their website... 

## Curricular courses
At the Hannover Medical School I'm offering two regular courses (roughly every six months) for MHH staff/students.

**1. Basic course in statistics** ( [e.g, Statistics in Laboratory Animal Science](https://www.mh-hannover.de/ztl-kurse.html#c155391) )  
**2. How to plan & design animal experiments** ( [e.g, Power analysis and preparation of applications for animal experiments](https://www.mh-hannover.de/ztl-kurse.html#c155391) )

The actual dates can be seen in the links (Website is in German). Both courses can be held in German and/or English.
If you are not associated to the MHH but interested in a course/lecture you can write me an email and we'll find a solution.





